import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { trpc } from "@/utils/trpc";
import { Feed } from "@/components/Feed/Feed";
import { CreateTask } from "@/components/CreateTask/CreateTask";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: tasks } = trpc.getAll.useQuery();
  return (
    <>
      <Head>
        <title>tRPC Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CreateTask />
        <Feed>
          <ul>
            {tasks &&
              tasks.map((task) => (
                <li key={task.id}>
                  <h2>{task.title}</h2>
                  <p>{task.content}</p>
                </li>
              ))}
          </ul>
        </Feed>
      </main>
    </>
  );
}
